server:
  port: 8080

# mysql配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 远程数据库
    url: jdbc:mysql://124.221.167.103:3306/ktp?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Aa@123456

  # 设置单次文件上传的大小限制
  servlet:
    multipart:
      max-file-size: 100MB

# 开启mybatis-plus控制台 SQL 日志打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

